#! /bin/bash

PYTHON_FOLDER=pythonENV

# Make Python Directory
mkdir ${PYTHON_FOLDER}

pyCurrent=`python ./Sources/isPython2.7`

if [ $pyCurrent -gt 0 ]
then
    echo "Python >= 2.7"
    echo "Extracting Python Libraries"
    tar -xzf ./Sources/pythonPackages/virtualenv-16.7.5.tar.gz -C ${PYTHON_FOLDER}

    echo "Creating Virtual Python Environment"
    python ./${PYTHON_FOLDER}/virtualenv-16.7.5/virtualenv.py --system-site-packages ./${PYTHON_FOLDER}/myPython

    echo "Installing Python Libraries"
    ./${PYTHON_FOLDER}/myPython/bin/pip install ./Sources/pythonPackages/pydicom-1.3.0.tar.gz
else
    echo "Python < 2.7"
    echo "Extracting Python Libraries"
    tar -xzf ./Sources/pythonPackages/virtualenv-15.2.0.tar.gz -C ${PYTHON_FOLDER}

    echo "Creating Virtual Python Environment"
    python ./${PYTHON_FOLDER}/virtualenv-15.2.0/virtualenv.py --system-site-packages ./${PYTHON_FOLDER}/myPython

    echo "Installing Python Libraries"
    ./${PYTHON_FOLDER}/myPython/bin/pip install ./Sources/pythonPackages/pydicom-0.9.9.tar.gz
fi

echo "Cleaning Up"
rm -rf ./Sources/pythonPackages/


echo "Python Environment Created at ./${PYTHON_FOLDER}/myPython"